In [ ]:
# The exclamation point in front of a command indicates that it should be run on the shell
# It's an escape hatch :)
!pip install numpy --upgrade

In [1]:
# numpy is almost always abbreviated as "np"
import numpy as np

In [2]:
# numpy arrays are called ndarrays
type(np.array([]))

numpy.ndarray

In [3]:
# Create an ndarray using a python array literal
array_one = np.array([1, 2, 3, 4])
array_one

array([1, 2, 3, 4])

In [4]:
# Create an ndarray from an existing python array
arr = [5, 6, 7, 8]
array_two = np.array(arr)
array_two

array([5, 6, 7, 8])

In [5]:
# The zeros function takes a tuple that specifies dimensionality, returning a zeroed out ndarray
# Numpy is more or less a matrix library, so matrix convensions apply
# Example: Matrices are generally specified as m-by-n, meaning rows-then-columns
# In the following case, "(4, 5)" means 4 rows by 5 columns
zeros_array = np.zeros((4, 5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# The 1's equivalent of the zeros function
ones_array = np.ones((4, 5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# A data type can be supplied when creating ndarrays using any of the many array creation functions https://numpy.org/doc/stable/reference/routines.array-creation.html
int16_ones_array = np.ones((4, 5), dtype=np.int16)
int16_ones_array

# Notice "dtype=int16" below

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [8]:
# Creates an ndarray without assigning values
# "empty, unlike zeros, does not set the array values to zero,
#  and may therefore be marginally faster. On the other hand,
#  it requires the user to manually set all the values in the
#  array, and should be used with caution."
# See: "Notes" under "empty" at https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty
empty_array = np.empty((4, 5))
empty_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Creates an ndarray with 1's in the diagnol, and 0's everywhere else.
eye_array = np.eye(5)
eye_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# "a range"
# Signature: (beginning:number inclusive, ending:number exclusive, step:number) -> ndarray
even_numbers_array = np.arange(2, 12, 2)
even_numbers_array

array([ 2,  4,  6,  8, 10])

In [11]:
# "a range"
# Signature 2: (ending:number exclusive) -> ndarray
first_ten_integers = np.arange(10)
first_ten_integers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# "a range" can also used with floats
float_arange_array = np.arange(2, 12, 0.5)
float_arange_array

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5])

In [13]:
# Multi-dimensional arrays can be created from nested arrays
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Multi-dimensional arrays can be created from an array of tuples
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# The shape of the array can be fetched using the shape attribute
# In this case we have 2 rows and 3 columns (remember, matrix conventions m-by-n)
np.array([(1, 2, 3), (4, 5, 6)]).shape

(2, 3)

In [16]:
# ndarrays can be reshaped (AKA the dimensionality can be changed)

a_vector = np.arange(9)
display("Vector", a_vector)

a_matrix = a_vector.reshape((3, 3))
display("Matrix", a_matrix)

'Vector'

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

'Matrix'

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# When using reshape, a sign missing dimension length
# can be auto calculated if -1 is supplied for that dimensions length.
# In this case 3 is specified for the number of rows,
# and the number of columns is auto calculated.
np.arange(9).reshape((3, -1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# NOTE: If you try to reshape to dimensions that don't exactly fit the data, an exception will be thrown.
# Example 1: np.arange(9).reshape((5, 12))
# Example 2: np.arange(9).reshape((2, 2))