In [1]:
import numpy as np

In [2]:
# display vs print

an_array = np.arange(5)

display(an_array)
print(an_array)

array([0, 1, 2, 3, 4])

[0 1 2 3 4]


In [3]:
# Multi-dimensional arrays get printed as arrays of arrays

print("1D")
print(np.arange(12), "\n")

print("2D")
print(np.arange(12).reshape((2, 6)), "\n")

print("3D")
print(np.arange(12).reshape((2, 3, 2)))

1D
[ 0  1  2  3  4  5  6  7  8  9 10 11] 

2D
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

3D
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# Large vectors will have middle elements removed
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [5]:
# Large matrices will have middle rows/columns/etc removed
print(np.arange(10000).reshape((100, 100)))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [6]:
print(np.arange(1000000).reshape((100, 100, 100)))

[[[     0      1      2 ...     97     98     99]
  [   100    101    102 ...    197    198    199]
  [   200    201    202 ...    297    298    299]
  ...
  [  9700   9701   9702 ...   9797   9798   9799]
  [  9800   9801   9802 ...   9897   9898   9899]
  [  9900   9901   9902 ...   9997   9998   9999]]

 [[ 10000  10001  10002 ...  10097  10098  10099]
  [ 10100  10101  10102 ...  10197  10198  10199]
  [ 10200  10201  10202 ...  10297  10298  10299]
  ...
  [ 19700  19701  19702 ...  19797  19798  19799]
  [ 19800  19801  19802 ...  19897  19898  19899]
  [ 19900  19901  19902 ...  19997  19998  19999]]

 [[ 20000  20001  20002 ...  20097  20098  20099]
  [ 20100  20101  20102 ...  20197  20198  20199]
  [ 20200  20201  20202 ...  20297  20298  20299]
  ...
  [ 29700  29701  29702 ...  29797  29798  29799]
  [ 29800  29801  29802 ...  29897  29898  29899]
  [ 29900  29901  29902 ...  29997  29998  29999]]

 ...

 [[970000 970001 970002 ... 970097 970098 970099]
  [970100 970101 970

In [7]:
# A global threshold can be set that dictates
# how many elements must exist to trigger to summarization

np.set_printoptions(threshold=10)
print(np.arange(20))

# Set the threshold to sys.maxsize to prevent summarization

np.set_printoptions(threshold=sys.maxsize)
print(np.arange(20))

[ 0  1  2 ... 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
