In [1]:
import numpy as np

In [2]:
vec_a = np.array([10, 10, 10])
vec_b = np.array([5, 5, 5])

In [3]:
# Pairwise Addition/Subraction/Multiplication/Division (And Many More!)
# See: https://numpy.org/doc/stable/reference/arrays.ndarray.html#arithmetic-matrix-multiplication-and-comparison-operations
print(vec_a + vec_b)
print(vec_a - vec_b)
print(vec_a * vec_b)
print(vec_a / vec_b)

[15 15 15]
[5 5 5]
[50 50 50]
[2. 2. 2.]


In [4]:
# Elementwise Scalar Operations

print(vec_a + 1)
print(vec_a - 1)
print(vec_a * 2)
print(vec_a / 2)
print(vec_a % 2)

[11 11 11]
[9 9 9]
[20 20 20]
[5. 5. 5.]
[0 0 0]


In [5]:
# Elementwise Boolean Operations

print(vec_a > 10)
print(vec_a <= 10)
print(vec_a == 10)
print(vec_a != 10)

[False False False]
[ True  True  True]
[ True  True  True]
[False False False]


In [6]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

In [7]:
# Pairwise Addition/Subtraction/Multiplication/Division

print(matrix_a + matrix_b)
print(matrix_a - matrix_b)
print(matrix_a * matrix_b)
print(matrix_a / matrix_b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
# Matrix Multiplication

print(matrix_a.dot(matrix_b))

print(np.dot(matrix_a, matrix_b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
# Aggregate and Range functions (There are many more!) https://numpy.org/doc/stable/reference/arrays.ndarray.html#calculation

print(matrix_a.sum())
print(matrix_a.min())
print(matrix_a.max())

10
1
4


In [10]:
# Aggregate and Range functions (There are many more!) https://numpy.org/doc/stable/reference/arrays.ndarray.html#calculation
# can be limited to an axis
# axis=0: iterate over rows
# axis=1: iterate over columns
# axis=n: iterate over n-th dimension

print("sum")
print(matrix_a.sum(axis=0))
print(matrix_a.sum(axis=1))

print("\nmin")
print(matrix_a.min(axis=0))
print(matrix_a.min(axis=1))

print("\nmax")
print(matrix_a.max(axis=0))
print(matrix_a.max(axis=1))

sum
[4 6]
[3 7]

min
[1 2]
[1 3]

max
[3 4]
[2 4]


In [13]:
# NDArrays can be dumped to disk (dump)
# or a string (dumps)

matrix_a.dump("data/dump.example")

matrix_a.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02K\x02\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X \x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'