In [1]:
import numpy as np

In [2]:
vec = np.arange(9) * 10
mat = vec.reshape((3, 3))

print("vec\n",
      vec,
      "\n\nmat\n",
      mat)

vec
 [ 0 10 20 30 40 50 60 70 80] 

mat
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [5]:
# Many function in numpy are "universal", meaning they operate on scalars, vectors, and matrices
# See: https://numpy.org/doc/stable/reference/routines.logic.html
# See: https://numpy.org/doc/stable/reference/routines.math.html
# There are probably other universal functions I don't have referenced above

print("is real: vec\n",
      np.isreal(vec),
      "\n\nis real: mat\n",
      np.isreal(mat),
      "\n\nsin: vec\n",
      np.sin(vec),
      "\n\nsin: mat\n",
      np.sin(mat),
      "\n\nmean: vec\n",
      np.mean(vec),
      "\n\nmedian: vec\n",
      np.median(vec))

is real: vec
 [ True  True  True  True  True  True  True  True  True] 

is real: mat
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

sin: vec
 [ 0.         -0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485
 -0.30481062  0.77389068 -0.99388865] 

sin: mat
 [[ 0.         -0.54402111  0.91294525]
 [-0.98803162  0.74511316 -0.26237485]
 [-0.30481062  0.77389068 -0.99388865]] 

mean: vec
 40.0 

median: vec
 40.0
