In [1]:
import numpy as np

In [3]:
vec = np.arange(1, 11) ** 2
vec

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
# Slicing can be from index to index (INCLUSIVE to EXCLUSIVE)
print(vec[2:6])

# From the beginning to an index (EXCLUSIVE)
print(vec[:6])

# From an index to the end (INCLUSIVE)
print(vec[6:])

[ 9 16 25 36]
[ 1  4  9 16 25 36]
[ 49  64  81 100]


In [12]:
# Reasonable negative slicing also works

print(vec[-5:-3])
print(vec[:-5])
print(vec[-5:])

[36 49]
[ 1  4  9 16 25]
[ 36  49  64  81 100]


In [14]:
# And mixing the two

print(vec[1:-5])
print(vec[-9:8])

[ 4  9 16 25]
[ 4  9 16 25 36 49 64]


In [22]:
# Indexing also supports stepping
# [beginning]:[ending]:step

print(vec[2:8:3])
print(vec[:8:3])
print(vec[::3])

[ 9 36]
[ 1 16 49]
[  1  16  49 100]


In [35]:
# And negatives of stepping as well

print(vec[8:2:-2])
print(vec[:2:-2])
print(vec[::-2])

print(vec[-2:-8:-2])
print(vec[-8:-2])

# Which can be used to reverse an ndarray
print(vec[::-1])

[81 49 25]
[100  64  36  16]
[100  64  36  16   4]
[81 49 25]
[ 9 16 25 36 49 64]
[100  81  64  49  36  25  16   9   4   1]
