In [72]:
import numpy as np

In [73]:
vec = np.arange(1, 11) ** 2
mat = vec.reshape((2, -1))

display(vec)
display(mat)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [74]:
# Iterating over a vector yields individual elements
for x in vec:
    print(x)

1
4
9
16
25
36
49
64
81
100


In [75]:
# Iterating over a matrix yields rows (by default)
for row in mat:
    print(row)

[ 1  4  9 16 25]
[ 36  49  64  81 100]


In [76]:
# "flatten" takes an n-dimensional ndarray and returns a 1-dimensional array
# "flatten" is row major, meaning it flattens an entire row before moving on to the next row

flat = mat.flatten()

display(type(flat))

for x in flat:
    print(x)

numpy.ndarray

1
4
9
16
25
36
49
64
81
100


In [77]:
# "flatten" can return an column major ndarray by passing in the "F" "order" flag
# See: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html
# Note: "F" stands for Fortran

flat_column_wise = mat.flatten(order="F")

for x in flat_column_wise:
    print(x)

1
36
4
49
9
64
16
81
25
100


In [78]:
# nditer class is similar to an IEnumerable from .NET, and enables similar iterations to "flatten"

display(type(np.nditer(vec)))

print("vec")
for x in np.nditer(vec):
    print(x)

print("\nmat")
for x in np.nditer(mat):
    print(x)

print("\nmat: column major")
for x in np.nditer(mat, order="F"):
    print(x)

numpy.nditer

vec
1
4
9
16
25
36
49
64
81
100

mat
1
4
9
16
25
36
49
64
81
100

mat: column major
1
36
4
49
9
64
16
81
25
100


In [79]:
# nditer supports many flags which can improve performance in certain situations
# or return data in different shapes
# See: https://numpy.org/doc/stable/reference/generated/numpy.nditer.html
# As an example the following flag when paired with the "F" order returns an array per column

columns = np.nditer(mat, order="F", flags=["external_loop"])

for col in columns:
    print(col)

[ 1 36]
[ 4 49]
[ 9 64]
[16 81]
[ 25 100]


In [80]:
# Mutability
# By default nditer is a readonly view of an ndarray
# this can be changed by supplying one or more of the many "op_flags"
# See: https://numpy.org/doc/stable/reference/generated/numpy.nditer.html
# The following example makes the nditer a read and write view over the ndarray
# The ellipses Represents a Reference to the current cell in the ndarray

mut_iter = np.nditer(mat, op_flags=["readwrite"])

print("before:")
display(mat)

for cell in mut_iter:
    cell[...] = cell * 2

print("after:")
display(mat)

before:


array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

after:


array([[  2,   8,  18,  32,  50],
       [ 72,  98, 128, 162, 200]])