In [2]:
import numpy as np

In [3]:
vec = np.arange(12)
mat = np.arange(12).reshape(3, -1)
mat2 = np.arange(12).reshape(4, -1)

display(vec)
display(mat)
display(mat2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
# "split" enables creating a array of equal length ndarrays
# NOTE: Supplying an split value that doesn't evenly split will throw an error
#       Example: np.split(np.array([1, 2, 3, 4, 5]), 3) because 5 isn't evenly divisible by 3

display(np.split(vec, 3))
display(np.split(vec, 4))

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [5]:
# "split" can also be called with an array of indices which represent the split points

np.split(vec, [2, 4, 10])

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7, 8, 9]), array([10, 11])]

In [6]:
# "hsplit" enables horizontally splitting an ndarray
# creating two horizontal pieces (by creating a vertical cut through the matrix)
# the name is confussing

np.hsplit(mat, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [7]:
# Similar to "split", "hsplit" also supports slicing on indices

np.hsplit(mat, [1, 3])

[array([[0],
        [4],
        [8]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [8]:
# "vsplit" is the vertical equivalent of "hsplit"

display(np.vsplit(mat2, 2))
display(np.vsplit(mat2, [1, 3]))

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [11]:
# vertical and row splits can be done using the split
# function and supplying an axis argument

display(np.split(mat2, 2, axis=0)) # split on rows (vertical split)
display(np.split(mat2, 3, axis=1)) # split on columns (horizontal split)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]