In [15]:
import numpy as np

In [20]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# "copy" performs a deep copy an ndarray

copy = vec.copy()
copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# if we update an element in our copy, the original
# ndarray is unaffected

copy[0] = 42

display(vec)
display(copy)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([42,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [23]:
# From the "base" attribute we can see that the resulting ndarray
# is NOT built on top of the original ndarray

print(copy.base is str_vec)
print(copy.base)

False
None
