In [19]:
import numpy as np
import csv

In [20]:
vec = np.arange(10) ** 2

In [21]:
# Beyond single integers, ndarrays can be indexed into using single dimensional arrays of integers

vec[[0, 2, 4, 6, 8]]

array([ 0,  4, 16, 36, 64])

In [22]:
# And N-dimensional ndarrays

indice_arr = np.array([[0, 1], [8, 9]])

vec[indice_arr]

array([[ 0,  1],
       [64, 81]])

In [23]:
# In both cases above, the shape of the
# output ndarray is the shape of the
# indices array

In [24]:
# NDArrays can also be indexed into when
# supplied multiple ndarrays, each representing
# a single dimension's index.
# Note: The shapes of the indices arrays must be identical.


square = np.arange(25).reshape(5, 5)
display("source", square)

row_indices = np.array([[0, 0], [1, 1]])
col_indices = np.array([[0, 4], [0, 4]])

out = square[row_indices, col_indices]
display("result", out)

# As we see below, the resulting ndarray
# has the same shape as the indices ndarrays,
# and when indexing into the source ndarray,
# a cell wise paring of the row and column
# indices is used.

'source'

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

'result'

array([[0, 4],
       [5, 9]])

In [25]:
# Beyond reading, dimension specific indexing can be used for writes
# Once again, the indices arrays have to be of the same shape,
# though their exact shape really doesn't matter (I think).


square_b = np.arange(25).reshape(5, 5)
display("source", square_b)

row_indices_b = np.array([[0, 0], [1, 1]])
col_indices_b = np.array([[0, 4], [0, 4]])

square_b[row_indices, col_indices] = 99
display("result", square_b)

'source'

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

'result'

array([[99,  1,  2,  3, 99],
       [99,  6,  7,  8, 99],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# And single dimensional indexing can also be used for writes

vec[[0, 9]] = 99
vec

array([99,  1,  4,  9, 16, 25, 36, 49, 64, 99])

In [39]:
# Mixing indexing styles is supported

display( square )
display( square[[0, 4], :2] )
display( square[np.array([0, 4]), :2] )

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1],
       [20, 21]])

array([[ 0,  1],
       [20, 21]])

In [47]:
# A boolean array or ndarray matching the size and shape
# of the original array can be used to filter to "True" indices

display("original", vec)

bool_indices = [True, False, True, False, True, False, True, False, True, False]
display("filtered", vec[bool_indices])


'original'

array([99,  1,  4,  9, 16, 25, 36, 49, 64, 99])

'filtered'

array([99,  4, 16, 36, 64])

In [50]:
# Putting it all together, the following
# example uses a universal filter to find
# indices that are not nan.

vec_with_nans = np.array([1, 2, np.nan, 4, 5, np.nan, 7, 8, 9, np.nan])
display("vec with nans", vec_with_nans)

bool_nan_indices = ~np.isnan(vec_with_nans)
display("bool nan indices", bool_indices)

display("non-nan elements", vec_with_nans[bool_nan_indices])

# tersly
tersely = vec_with_nans[~np.isnan(vec_with_nans)]
display("tersely", tersely)

'vec with nans'

array([ 1.,  2., nan,  4.,  5., nan,  7.,  8.,  9., nan])

'bool nan indices'

[True, False, True, False, True, False, True, False, True, False]

'non-nan elements'

array([1., 2., 4., 5., 7., 8., 9.])

array([1., 2., 4., 5., 7., 8., 9.])