In [1]:
import numpy as np

In [2]:
vec = np.arange(10)
display(vec)

mat = np.arange(25).reshape(5, 5)
display(mat)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
# Using boolean returning operator with an NDArray
# returns a boolean NDArray representing an element
# wise return of the operator application. The resulting
# NDArray is the same shape as the input NDArray

vec_bools = vec < 5
display(vec_bools)

mat_bools = (mat <= 12) | (mat > 20)
display(mat_bools)

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [6]:
# A bool array or NDArray passed into the index of
# an NDArray array, behaves as a filter

select_first_five = [True, True, True, True, True, False, False, False, False, False]
vec[select_first_five]

array([0, 1, 2, 3, 4])

In [13]:
# Aggregate functions such as sum, count_nonezero, all, etc.
# can accept Boolean NDArrays or arrays, treating
# True as 1 and False as 0.

vec_bools = [True, True, True, True, True, False, False, False, False]
vec_bools_nd = np.array(bools)

display( np.count_nonzero(vec_bools) )
display( np.count_nonzero(vec_bools_nd) )

display( np.sum(vec_bools) )
display( np.sum(vec_bools_nd) )


mat_bools = [[True, True, True, True, True],
             [False, False, False, False, False],
             [False, False, False, False, False],
             [False, False, False, False, False],
             [False, False, False, False, False]]
mat_bools_nd = np.array(mat_bools)

display( np.count_nonzero(mat_bools) )
display( np.count_nonzero(mat_bools_nd) )

display( np.sum(mat_bools) )
display( np.sum(mat_bools_nd) )

5

5

5

5

5

5

5

5

5

5

In [14]:
# And since we can use boolean returning operators
# to transform numeric ndarrays into boolean ndarrays
# we can count numeric values that match a certain

display( np.count_nonzero(vec < 5) )
display( np.sum(vec < 5) )

display( np.count_nonzero(mat < 5) )
display( np.sum(mat < 5) )

5

5

5

5

In [16]:
# Aggregating can also be done per axis
# In this case we're counting the number
# of elements that match a filter in a given row

np.sum(mat <= 12, axis=1)

array([5, 5, 3, 0, 0])

In [17]:
# Multiple filters can be used together

np.sum((mat <= 12) | (mat > 20), axis=1)

array([5, 5, 3, 0, 4])