In [2]:
import numpy as np

In [6]:
# "Broadcasting" is numpy's word for
# how it treats different NDArray/Scalar
# shapes during arithemetic operations.
# See: https://numpy.org/devdocs/user/theory.broadcasting.html
# See: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [7]:
# When performing scalar arithmetic against an NDarray,
# we basically have function application over a collection.
# AKA given a collection, apply a function, and get a
# collection of the same shape back but with the function
# applied to each element.

vec = np.arange(5)
mat = np.arange(25).reshape(5, 5)
mat2 = np.arange(125).reshape(5, 5, 5)

display( vec * 2 )
display( mat * 2 )
display( mat2 * 2 )

array([0, 2, 4, 6, 8])

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

array([[[  0,   2,   4,   6,   8],
        [ 10,  12,  14,  16,  18],
        [ 20,  22,  24,  26,  28],
        [ 30,  32,  34,  36,  38],
        [ 40,  42,  44,  46,  48]],

       [[ 50,  52,  54,  56,  58],
        [ 60,  62,  64,  66,  68],
        [ 70,  72,  74,  76,  78],
        [ 80,  82,  84,  86,  88],
        [ 90,  92,  94,  96,  98]],

       [[100, 102, 104, 106, 108],
        [110, 112, 114, 116, 118],
        [120, 122, 124, 126, 128],
        [130, 132, 134, 136, 138],
        [140, 142, 144, 146, 148]],

       [[150, 152, 154, 156, 158],
        [160, 162, 164, 166, 168],
        [170, 172, 174, 176, 178],
        [180, 182, 184, 186, 188],
        [190, 192, 194, 196, 198]],

       [[200, 202, 204, 206, 208],
        [210, 212, 214, 216, 218],
        [220, 222, 224, 226, 228],
        [230, 232, 234, 236, 238],
        [240, 242, 244, 246, 248]]])

In [5]:
# Given two NDArrays, if the second NDArray has
# the same number of rows and one column it can
# be applied columnwise per element, or if the
# second NDArray has the same number of columns
# and one row, it can be applied rowwise per
# element

mat = np.arange(15).reshape(5, 3)

vec1 = np.arange(5).reshape(5, 1)

vec2 = np.arange(3)

display( mat )
display( vec1 )
display( vec2 )

display( mat + vec1 )
display( mat + vec2 )

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[0],
       [1],
       [2],
       [3],
       [4]])

array([0, 1, 2])

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [3]:
# Given two NDArrays of the same shape,
# arithmetic operations are applied elementwise.

vec1 = np.arange(5)
vec2 = np.arange(5)

mat1 = np.arange(25).reshape(5, 5)
mat2 = np.arange(25).reshape(5, 5)

display( vec1 + vec2 )
display( mat1 + mat2 )

array([0, 2, 4, 6, 8])

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [ ]:
# These concepts generalize out to higher dimensional arrays.

# Boardcasting is designed to be memory efficient instead of allocating c-style arrays.

# Also, broadcasting is designed to efficient, reducing marshaling yet implementing 
# the raw arithmetic in c.


# SEE: https://numpy.org/devdocs/user/theory.broadcasting.html
# SEE: https://numpy.org/doc/stable/user/basics.broadcasting.html
# Broadcasting is designed to memory