In [1]:
import numpy as np

In [5]:
mat1 = np.arange(15).reshape(3, 5)
mat2 = np.arange(15, 30).reshape(3, 5)

display( mat1 )
display( mat2 )

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
# np.concatenate can be used to concatenate
# multiple NDArrays together.

np.concatenate((mat1, mat2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [8]:
# An axis argument can be provided
# that specifies along which axis
# the concatenation should be performed.
# axis is defaulted to 0

np.concatenate((mat1, mat2), axis=1)

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [14]:
# Convenience functions vstack and hstack
# are provided that potentially make
# concatenation a little more intuitive

display( np.vstack((mat1, mat2)) )
display( np.hstack((mat1, mat2)) )

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [18]:
# The np.stack function takes a collection
# of NDArrays and returns a new NDArray
# COMPRISED OF THE SUPPLIED NDARRAYS
# NOT ELEMENTS OF THE SUPPLIED NDARRAYS

np.stack((mat1, mat2), axis=0)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])